backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "blog_en"
  #   label: "Blog (English)"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   filter: {field: "language", value: en}
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Path", name: "path", widget: "string"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     # - {label: "Language", name: "language", widget: "select", options: ["en", "ja"]}
  #     - {label: "Body", name: "body", widget: "markdown"}

  # - name: "blog_ja"
  #   label: "Blog (Japanese)"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   filter: {field: "language", value: ja}
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Path", name: "path", widget: "string"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     # - {label: "Language", name: "language", widget: "select", options: ["en", "ja"]}
  #     - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "ja"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Pages - EN"
    label: "Pages - EN"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    files:
      - file: "src/pages/en/about/about.md"
        label: "About - EN"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/en/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    create: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
    files:
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - file: "src/pages/jobs/jobs.md"
        label: "Jobs Page"
        name: "jobs"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jobs-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/jobs"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/contact/"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/product/product.md"
        label: "Product Page"
        name: "product"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/product"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

